.Dd July 06, 2011
.Dt RANDSLEEP 1
.Os
.
.
.Sh NAME
.
.Nm randsleep
.Nd Execute program after sleeping for a random time
.
.
.Sh SYNOPSIS
.
.Nm
.Ar time command args ...
.
.
.Sh VERSION
.
This manual documents
.Nm
version 0.0
.
.
.Sh DESCRIPTION
.
.Nm
executes
.Ar command
after sleeping for up to
.Ar time
seconds.
It is intended for use in cronjobs and similar.
.
.
.Sh RATIONALE
.
.Qq sleep $(( RANDOM % 120 )); do_stuff
and similar constructs are frequently used in crontab entries to decrease load
spikes when several entries are executed at the same time.
.
.Pp
.
However, in certain shells
.Pq such as Cm dash
.Ev $RANDOM
may not be available.
This leads to workarounds involving, for
example, /dev/urandom and cksum.  Since repeating the same workarounds over
and over seems somewhat pointless, this tool was created.
.
.
.Sh AUTHOR
.
Copyright (C) 2011 Daniel Friesel
.Aq derf@finalrewind.org .
.
.
.Sh LICENSE
.
You just DO WHAT THE FUCK YOU WANT TO.
