.Dd July 06, 2011
.Dt RANDSLEEP 1
.Os
.
.
.Sh NAME
.
.Nm randsleep
.Nd Execute program after sleeping for a random time
.
.
.Sh SYNOPSIS
.
.Nm
.Ar time command args ...
.
.
.Sh VERSION
.
This manual documents
.Nm
version 0.0
.
.
.Sh DESCRIPTION
.
.Nm
executes
.Ar command
after sleeping for up to
.Ar time
seconds.
It is intended for use in cronjobs and similar.
.
.
.Sh AUTHOR
.
Copyright (C) 2011 Daniel Friesel
.Aq derf@finalrewind.org .
.
.
.Sh LICENSE
.
You just DO WHAT THE FUCK YOU WANT TO.
